require 'logging'
require 'setter'
require 'single'
require 'initializer'

require 'output/devices'
require 'output/writer_macro'
require 'output/output'
require 'output/build_logger'
require 'output/writer'
