require_relative 'proofs_init'

load 'output/output_demo.rb'
load 'output/logging_util.rb'
load 'output/change_writer_level_demo.rb'
load 'output/writer_macro.rb'
load 'output/writer.rb'
load 'output/writer_naming.rb'
load 'output/writer_attributes.rb'
load 'output/pushing_a_device_to_a_writer.rb'
load 'output/popping_a_device_from_a_writer.rb'
load 'output/pushing_a_device_to_output.rb'
