#!/usr/bin/env ruby

require_relative 'proofs_init'

files = Dir.glob("proofs/output/**/*.rb")
files = files.concat Dir.glob("proofs/demos/**/*.rb")

files.reject!{|item| /_sketch/ =~ item}


Proof::Runner::Suite.run files
